src/EasyTrainTickets3.WebUI/Models/MyTicketViewModel.cs
using EasyTrainTickets.Domain.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EasyTrainTickets3.WebUI.Models
{
    public class MyTicketViewModel
    {
        public List<Ticket> Tickets { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

src/EasyTrainTickets3.WebUI/Controllers/MyTicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyTrainTickets.Domain.Data;
using EasyTrainTickets3.WebUI.Models;
using EasyTrainTickets.Domain.Services;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity.Owin;

namespace EasyTrainTickets3.WebUI.Controllers
{
    [Authorize]
    public class MyTicketController : Controller
    {
        private IUnitOfWorkFactory unitOfWorkFactory;
        private MyTicketModel myTicketModel;
        private readonly int PageSize = 5;

        public MyTicketController(IUnitOfWorkFactory _unitOfWorkFactory)
        {
            unitOfWorkFactory = _unitOfWorkFactory;
            myTicketModel = new MyTicketModel();
        }
        // GET: MyTicket
        public ActionResult Index(int page = 1)
        {
            MyTicketViewModel viewModel = new MyTicketViewModel();
            using (var dbContext = unitOfWorkFactory.CreateUnitOfWork())
            {
                PagingInfo PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize
                };
                List<Ticket> tickets = myTicketModel.GetTicketsUser(dbContext, PagingInfo);
                viewModel.Tickets = tickets;
                viewModel.PagingInfo = PagingInfo;
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteTicket(string stringTicket)
        {
            Ticket ticket;
            try
            {
                ticket = JsonConvert.DeserializeObject<Ticket>(stringTicket);
            }
            catch
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd" });
            }
            if (ticket == null || ticket.ConnectionPath.StartTime < DateTime.Now.AddHours(1))
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Czas odjazdu minął." });
            using (var dbContext = unitOfWorkFactory.CreateTransactionalUnitOfWork())
            {
                ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                if (!myTicketModel.DeleteTicket(ticket, dbContext, userManager))
                    return View("MyError", new ErrorViewModel() { ErrorMessage = "Z przykrością informujemy, że ten bilet został już wcześniej usunięty" });
                dbContext.Accept();
            }
            return RedirectToAction("Index");
        }
    }
}

src/EasyTrainTickets3.WebUI/Views/MyTicket/Index.cshtml
@model EasyTrainTickets3.WebUI.Models.MyTicketViewModel

@{
    ViewBag.Title = "Moje bilety";
}

<script>
    jQuery.fn.clickToggle = function (a, b) {
        function cb() { [b, a][this._tog ^= 1].call(this); }
        return this.on("click", cb);
    };

    $(document).ready(function () {
 $('.details').hide();
 $('.ticket').clickToggle(
    	function() {
           $(this).next('.details').slideDown();
        },
        function() {
           $(this).next('.details').fadeOut();
      }
    ); // koniec funkcji toggle
}); // koniec funkcji ready
</script>

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        @foreach (var ticket in Model.Tickets)
        {
            @Html.Partial("_TicketPartial", ticket)
        }
    </div>
    <div class="pager pull-right">
        @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index", new { page = x }))
    </div>
    @using (Html.BeginForm("Index", "Home"))
    {
        <div class="text-center">
            <input class="btn btn-warning" type="submit" value="Cofnij" />
        </div>
    }
</div>

src/EasyTrainTickets3.WebUI/Views/MyTicket/_TicketPartial.cshtml
@model EasyTrainTickets.Domain.Services.Ticket

<div class="row ticket">
    <div class="row">
        <div class="col-lg-2">
            @Model.ConnectionPath.StartStation
        </div>
        <div class="col-lg-2">
            <span>@Model.ConnectionPath.StartTime.ToShortDateString()</span>
        </div>
        <div class="col-lg-1">
            <span>@Model.ConnectionPath.StartTime.ToShortTimeString()</span>
        </div>
        <div class="col-lg-2">
            Czas podróży:
        </div>
        <div class="col-lg-2">
            Przesiadki:  @Model.ConnectionPath.Changes
        </div>
        <div class="col-lg-2">

            @foreach (string pic in Model.ConnectionPath.SourcePictures)
            {
                <img src="@pic" />

            }
        </div>

        @using (Html.BeginForm("DeleteTicket", "MyTicket"))
        {
            <div class="col-lg-1">
                @Html.Hidden("stringTicket", Model.JsonString)
                <input id="delete" class="btn btn-success" type="submit" disabled=@(DateTime.Now.AddHours(1)>Model.ConnectionPath.StartTime) value="Usuń bilet" />
            </div>
        }
    </div>
    <div class="row">
        <div class="col-lg-2">
            @Model.ConnectionPath.EndStation
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-1">
            @Model.ConnectionPath.EndTime.ToShortTimeString()
        </div>
        <div class="col-lg-2">
            @string.Format("{0}:{1:00} h", Model.ConnectionPath.JourneyTime.Hours, Model.ConnectionPath.JourneyTime.Minutes)
        </div>
        <div class="col-lg-2">
            Cena:  @Model.Price zł
        </div>
        <div class="col-lg-2">
            @foreach (var key in Model.Discounts.Keys)
            {
                if(Model.Discounts[key] > 0)
                {
                    <span>@key.Type: @Model.Discounts[key]<br/></span>
                }
            }
        </div>
    </div>
</div>
<div class="row details">
    @foreach (var s in Model.Way)
    {
        <pre>@s</pre>
    }
</div>
<hr />