src/EasyTrainTickets3.WebUI/Models/BuyTicketViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using EasyTrainTickets.Domain.Data;
using EasyTrainTickets.Domain.Model;
using Newtonsoft.Json;
using EasyTrainTickets.Domain.Services;
using System.Web.Script.Serialization;

namespace EasyTrainTickets3.WebUI.Models
{
    public class BuyTicketDiscountViewModel
    {
        public string conIds;
        public List<Discount> discounts;
        public int[] qualityDiscounts;

        public string SelectedDiscount { get; set; }

        public BuyTicketDiscountViewModel() { }

        public BuyTicketDiscountViewModel(IUnitOfWorkFactory unitOfFactory)
        {
            using (IEasyTrainTicketsDbEntities dbContext = unitOfFactory.CreateUnitOfWork())
            {
                discounts = dbContext.Discounts.ToList();
                qualityDiscounts = new int[discounts.Count];
            }
        }
    }

    public class BuyTicketSummaryPriceViewModel
    {
        public string ConIds { get; set; }
        public string ListDiscount { get; set; }
        public decimal Price { get; set; }
        public List<string> Way { get; set; }
        public Dictionary<Discount, int> Dict { get; set; }

        public BuyTicketSummaryPriceViewModel() { }

        public BuyTicketSummaryPriceViewModel(IEasyTrainTicketsDbEntities dbContext, string conIds, string qualityDiscount)
        {
            List<int> qualDiscount = JsonConvert.DeserializeObject<int[]>(qualityDiscount).ToList();
            Dict = new Dictionary<Discount, int>();
            List<Discount> discounts = dbContext.Discounts.ToList();
            for (int i = 0; i < discounts.Count; i++)
            {
                Dict.Add(discounts[i], qualDiscount[i]);
            }
            List<int> list = new List<int>();
            foreach (var key in Dict.Keys) list.Add(Dict[key]);
            ListDiscount = JsonConvert.SerializeObject(list);

            ConIds = conIds;
            List<ConnectionPart> conParts = JsonConvert.DeserializeObject<List<ConnectionPart>>(conIds);
            ConnectionPath conPath = new ConnectionPath() { ConnectionsParts = conParts };
            conPath.Initialize();
            decimal count = 0;
            foreach(var key in Dict.Keys)
            {
                count += (decimal)(Dict[key] * key.Percent);
            }
            Price = Math.Round(count * conPath.Price, 2);
            conPath.WriteConnection();
            Way = conPath.Way;
        }
    }

    public class TicketViewModel
    {
        public List<int> ListDiscounts { get; set; }
        public List<int[]> Seats { get; set; }
        public List<ConnectionPart> ConnectionsParts { get; set; }
        public string SourcePicture { get; set; }
        public List<int> FreeSeats { get; set; }
        public List<int> SeatsChoose { get; set; }
        public string FromStation { get; set; }
        public string EndStation { get; set; }
        public int Count { get; set; }
        public int CountParts { get; set; }
        public List<string> Way { get; set; }
        public decimal Price { get; set; }

        [ScriptIgnore]
        [JsonIgnore]
        public string JsonString
        {
            get
            {
                return JsonConvert.SerializeObject(this);
            }
        }

        public TicketViewModel() { }

        public TicketViewModel(string conIds, string dict, decimal price)
        {
            ListDiscounts = JsonConvert.DeserializeObject<List<int>>(dict);
            ConnectionsParts = JsonConvert.DeserializeObject<List<ConnectionPart>>(conIds);
            Count = 0;
            Seats = new List<int[]>();
            foreach (var i in ListDiscounts) Count += i;
            Way = new List<string>();
            Price = price;
        }
    }

}

src/EasyTrainTickets3.WebUI/Controllers/BuyTicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyTrainTickets.Domain.Services;
using EasyTrainTickets.Domain.Data;
using EasyTrainTickets3.WebUI.Models;
using System.Web.Helpers;
using Newtonsoft.Json;
using EasyTrainTickets.Domain.Model;
using Microsoft.AspNet.Identity.Owin;

namespace EasyTrainTickets3.WebUI.Controllers
{
    [Authorize]
    public class BuyTicketController : Controller
    {
        IUnitOfWorkFactory unitOfFactory;
        BuyTicketModel buyTicketModel;

        public BuyTicketController(IUnitOfWorkFactory _unitOfWork)
        {
            unitOfFactory = _unitOfWork;
            buyTicketModel = new BuyTicketModel();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        // Post: BuyTicket
        [HttpPost]
        public ActionResult Index(string conIds)
        {
            List<ConnectionPart> conParts = new List<ConnectionPart>();
            try
            {
                conParts = JsonConvert.DeserializeObject<List<ConnectionPart>>(conIds);
            }
            catch
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd." });
            }
            if(conParts.Count==0)
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd." });
            if (conParts.FirstOrDefault().StartTime < DateTime.Now.AddHours(1))
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Czas odjazdu minął." });
            BuyTicketDiscountViewModel discountView = new BuyTicketDiscountViewModel(unitOfFactory);
            discountView.conIds = conIds;
            return View(discountView);
        }

        [HttpPost]
        public ActionResult SummaryPrice(string SelectedDiscount, string conIds)
        {
            List<int> qualDiscount;
            try
            {
                qualDiscount = JsonConvert.DeserializeObject<int[]>(SelectedDiscount).ToList();
            }
            catch
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wybrane zniżki mają być liczbami." });
            }
            if (qualDiscount == null || qualDiscount.Sum() == 0 || qualDiscount.Count != 4)
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wybierz coś." });
            }
            foreach (var discount in qualDiscount)
            {
                if(discount<0 || discount>5)
                    return View("MyError", new ErrorViewModel() { ErrorMessage = "Wybrane ilości mają być liczbami od 0 do 5." });
            }
            BuyTicketSummaryPriceViewModel viewModel;
            using (IEasyTrainTicketsDbEntities dbContext = unitOfFactory.CreateUnitOfWork())
            {
                viewModel = new BuyTicketSummaryPriceViewModel(dbContext, conIds, SelectedDiscount);
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult RandomSeats(string conIds, string dictDiscount, decimal price)
        {
            TicketViewModel viewModel = new TicketViewModel(conIds, dictDiscount, price);

            using (IEasyTrainTicketsDbEntities dbContext = unitOfFactory.CreateUnitOfWork())
            {
                do
                {
                    if (!buyTicketModel.NextPart(viewModel, dbContext))
                        return View("MyError", new ErrorViewModel() { ErrorMessage = "Z przykrością informujemy, że nie ma wystarczającej ilości miejsc w wybranym połączeniu"});


                    viewModel.SeatsChoose = viewModel.FreeSeats.GetRange(0, viewModel.Count);
                } while (!buyTicketModel.IsEnd(viewModel));
            }
            ModelState.Clear();
            return View("SummaryReservation", viewModel);
        }

        [HttpPost]
        public ActionResult PrepareReserveSeats(string conIds, string dictDiscount, decimal price)
        {
            TicketViewModel viewModel;
            try
            {
                viewModel = new TicketViewModel(conIds, dictDiscount, price);
            }
            catch
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd." });
            }
            using (IEasyTrainTicketsDbEntities dbContext = unitOfFactory.CreateUnitOfWork())
            {
                if (!buyTicketModel.NextPart(viewModel, dbContext))
                    return View("MyError", new ErrorViewModel() { ErrorMessage = "Z przykrością informujemy, że nie ma wystarczającej ilości miejsc w wybranym połączeniu" });
            }
            
            return View("ReserveSeats", viewModel);
        }

        [HttpPost]
        public ActionResult ReserveSeats(string ticket, TicketViewModel ticketViewModel)
        {
            TicketViewModel viewModel;
            try
            {
                viewModel = JsonConvert.DeserializeObject<TicketViewModel>(ticket);
            }
            catch
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd." });
            }
            if(viewModel == null)
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd." });
            viewModel.SeatsChoose = ticketViewModel.SeatsChoose;
            if(viewModel.SeatsChoose.Count != viewModel.Count)
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wybrano niepoprawną liczbę miejsc." });
            using (IEasyTrainTicketsDbEntities dbContext = unitOfFactory.CreateUnitOfWork())
            {
                if (!buyTicketModel.NextPart(viewModel, dbContext))
                    return View("MyError", new ErrorViewModel() { ErrorMessage = "Z przykrością informujemy, że nie ma wystarczającej ilości miejsc w wybranym połączeniu" });
            }
            ModelState.Clear();
            if (buyTicketModel.IsEnd(viewModel)) return View("SummaryReservation", viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult BuyTicket(string ticket)
        {
            TicketViewModel viewModel;
            try
            {
                viewModel = JsonConvert.DeserializeObject<TicketViewModel>(ticket);
            }
            catch
            {
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd" });
            }
            if (viewModel == null)
                return View("MyError", new ErrorViewModel() { ErrorMessage = "Wystąpił nieoczekiwany błąd." });
            using (ITransactionalData dbContext = unitOfFactory.CreateTransactionalUnitOfWork())
            {
                ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                bool ok = buyTicketModel.BuyTicket(viewModel, dbContext, userManager);

                if (ok)
                {
                    dbContext.Accept();
                }
                else
                {
                    return View("MyError", new ErrorViewModel() { ErrorMessage = "Z przykrością informujemy, że ktoś był szybszy i zajął twoje miejsce" });
                }
            }

            return View("MySuccess", new ErrorViewModel() { ErrorMessage = "Transakcja przebiegła poprawnie. Bilet został zakupiony." });
        }
    }
}

src/EasyTrainTickets3.WebUI/Views/BuyTicket/Index.cshtml
@model EasyTrainTickets3.WebUI.Models.BuyTicketDiscountViewModel

@{
    ViewBag.Title = "Wybierz ulgi";
}
<script>
    function validate() {
        var count = 0;
        $('.num').each(function () {
            count += $(this).val();
            if (count == 0) $(':input[type="submit"]').prop('disabled', true);
            else
                $(':input[type="submit"]').prop('disabled', false);
        }); // koniec funkcji each
    }
    $(document).ready(function () {
        $('.dalej').click(function () {
            var disc = new Array();
            $('.num').each(function () {
                disc.push($(this).val());
            }); // koniec funkcji each
            $('#SelectedDiscount').val(JSON.stringify(disc));
        });// koniec funkcji click

        validate();

        $('.num').change(function () {
            validate();
        })// koniec funkcji change
    }); // koniec funkcji ready
</script>

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        <h4>Wybierz ulgi:</h4>
        <hr/>
        @using (Html.BeginForm("SummaryPrice", "BuyTicket"))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            for (int i = 0; i < Model.discounts.Count; i++)
            {
                <div class="form-group">
                    @Model.discounts[i].Type:
                    <input class="num" id=@i type="number" min="0" max="5" value="@Model.qualityDiscounts[i]"/>
                </div>
            }
            <hr/>
            @Html.Hidden("SelectedDiscount")
            @Html.Hidden("conIds", Model.conIds)
            <div class="text-center dalej">
                <input class="btn btn-success" type="submit" value="Dalej" />
            </div>
        }
        </div>
    </div>

src/EasyTrainTickets3.WebUI/Views/BuyTicket/ReserveSeats.cshtml
@model EasyTrainTickets3.WebUI.Models.TicketViewModel

@{
    ViewBag.Title = "Wybór miejsc";
}
<script>
    function validate() {
        var count = 0;
        $.each($('.list option:selected'), function (index, value) {
            count += 1;
        });
        if(count == @Model.Count) $(':input[type="submit"]').prop('disabled', false);
        else
            $(':input[type="submit"]').prop('disabled', true);
    }
    $(document).ready(function () {
        validate();

        $('.list').change(function () {
            validate();
        }); // koniec funkcji change
    }); // koniec funkcji ready
</script>

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        <span>Zarezerwowany fragment połączenia:<br /></span>
        @foreach (var s in Model.Way)
        {
            <pre>@s</pre>
        }
        <p>Zarezerwuj na część:</p>
        <pre class="text-center">@Model.FromStation ==> @Model.EndStation</pre>
        <p>Wybierz dokładnie miejsc: @Model.Count. Do zaznaczenia wielu miejsc przytrzymaj przycisk Ctrl</p>
        @using (Html.BeginForm("ReserveSeats", "BuyTicket"))
        {
            <div class="row">
                <div class="col-lg-1">
                    @Html.ListBoxFor(m => m.SeatsChoose, new MultiSelectList(Model.FreeSeats), new { @class = "list", @style = "height: 200px; width: 100 px" })
                </div>
                <div class="col-lg-offset-1">
                    <img src="@Model.SourcePicture"/>
                </div>
            </div>
            @Html.Hidden("ticket", Model.JsonString)
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Dalej" />
            </div>
        }
        </div>
    </div>

src/EasyTrainTickets3.WebUI/Views/BuyTicket/SummaryPrice.cshtml
@model EasyTrainTickets3.WebUI.Models.BuyTicketSummaryPriceViewModel

@{
    ViewBag.Title = "Wybierz sposób rezerwacji";
}
<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        @foreach (var s in Model.Way)
        {
            <pre>@s</pre>
        }
        <div class="row" style="font-size: 24px">Cena: @Model.Price zł </div>

        @using (Html.BeginForm("RandomSeats", "BuyTicket"))
        {
            @Html.Hidden("dictDiscount", Model.ListDiscount)
            @Html.Hidden("conIds", Model.ConIds)
            @Html.Hidden("Price", Model.Price)
            <div class="col-lg-2 col-lg-offset-2">
                <input class="btn btn-success" type="submit" value="Losowy wybór miejsca" />
            </div>
        }
        @using (Html.BeginForm("PrepareReserveSeats", "BuyTicket"))
        {
            @Html.Hidden("dictDiscount", Model.ListDiscount)
            @Html.Hidden("conIds", Model.ConIds)
            @Html.Hidden("Price", Model.Price)
            <div class="col-lg-2 col-lg-offset-3">
                <input class="btn btn-success" type="submit" value="Ręczny wybór miejsca" />
            </div>
        }
    </div>
</div>

src/EasyTrainTickets3.WebUI/Views/BuyTicket/SummaryReservation.cshtml
@model EasyTrainTickets3.WebUI.Models.TicketViewModel

@{
    ViewBag.Title = "Szczegóły biletu";
}

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">

        @foreach (var s in Model.Way)
        {
            <pre>@s</pre>
        }
       <div class="row" style="font-size: 24px ">Cena: @Model.Price zł </div>
        @using (Html.BeginForm("BuyTicket", "BuyTicket"))
        {
            @Html.Hidden("ticket", Model.JsonString)
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Kup bilet" />
            </div>
        }
     </div>
</div>