src/EasyTrainTickets3.WebUI/Models/AddConnectionsViewModels.cs
using EasyTrainTickets.Domain.Model;
using EasyTrainTickets.Domain.Data;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EasyTrainTickets3.WebUI.Models
{
    public class DateViewModel
    {
        public DateTime Date { get; set; }
    }

    public class ConnectionViewModel
    {
        public Connection Connection { get; set; }

        [JsonIgnore]
        public string JsonString
        {
            get
            {
                return JsonConvert.SerializeObject(this.Connection);
            }
        }
        [JsonIgnore]
        public List<string> Way
        {
            get
            {
                List<string> way = new List<string>();
                foreach(var conPart in Connection.Parts)
                {
                    way.Add(string.Format("{0,15} => {1,15}   Odjazd: {2,7}   Przyjazd: {3,7}", conPart.Route.From,
                        conPart.Route.To, conPart.StartTime.ToShortTimeString(), conPart.EndTime.ToShortTimeString()));
                }

                return way;
            }
        }
    }

    public class ListConnectionsViewModel
    {       
        public List<ConnectionViewModel> ListConnections { get; set; }
        public PagingInfo PagingInfo { get; set; }

        public ListConnectionsViewModel()
        {
            ListConnections = new List<ConnectionViewModel>();
        }

        public void Show(List<Connection> connections, PagingInfo pagingInfo)
        {
            PagingInfo = pagingInfo;
            ListConnections = new List<ConnectionViewModel>();

            foreach (Connection con in connections.Skip((pagingInfo.CurrentPage - 1) * pagingInfo.ItemsPerPage).Take(pagingInfo.ItemsPerPage).ToList())
            {
                ListConnections.Add(new ConnectionViewModel() { Connection = con });
            }
        }
    }

    public class AddConnectionViewModel
    {
        public ConnectionViewModel Connection { get; set; }

        public DateTime StartTime { get; set; }
        public TimeSpan TimeOfDay { get; set; }
        [Required]
        public int StopTime { get; set; }
        [Required]
        public int Variance { get; set; }
        public List<string> AvailableRoutes { get; set; }
        [Required]
        public String SelectRoute { get; set; }
        public List<string> Trains { get; set; }
        [Required]
        public string SelectTrain { get; set; }
        [Required]
        public string Name { get; set; }

        public AddConnectionViewModel()
        {
            AvailableRoutes = new List<string>();
            Connection = new ConnectionViewModel();
        }
        public AddConnectionViewModel(IEasyTrainTicketsDbEntities dbContext)
        {
            List<Train> trains = dbContext.Trains.ToList();
            Trains = new List<string>();
            foreach(var t in trains)
            {
                Trains.Add(String.Format("{0}. {1}", t.Id, t.Type));
            }
        }

    }

}

src/EasyTrainTickets3.WebUI/Controllers/AddConnectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyTrainTickets3.WebUI.Models;
using EasyTrainTickets.Domain.Model;
using Newtonsoft.Json;
using EasyTrainTickets.Domain.Data;

namespace EasyTrainTickets3.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AddConnectionsController : Controller
    {
        IUnitOfWorkFactory unitOfWorkFactory;
        private int PageSize = 20;
        private AddConnectionModel addConnectionModel;
        public AddConnectionsController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            this.unitOfWorkFactory = unitOfWorkFactory;
            addConnectionModel = new AddConnectionModel();
        }
        // GET: AddConnections
        public ActionResult Index()
        {
            DateViewModel viewModel = new DateViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteConnection(int? page, string stringConnection)
        {
            Connection connection = JsonConvert.DeserializeObject<Connection>(stringConnection);
            List<Connection> connections = Session["connections"] as List<Connection>;
            connections.RemoveAll(con => con.StartPlace == connection.StartPlace && con.EndPlace == connection.EndPlace && 
            con.Name == connection.Name && con.Parts.First().StartTime == connection.Parts.First().StartTime);

            PagingInfo PagingInfo = new PagingInfo() { CurrentPage = (int)page, ItemsPerPage = PageSize, TotalItems = connections.Count };
            ListConnectionsViewModel viewModel = new ListConnectionsViewModel();
            viewModel.Show(connections, PagingInfo);
            Session["connections"] = connections;
            ModelState.Clear();

            return View("ListConnections", viewModel);
        }

        [HttpPost]
        public ActionResult AddConnections(DateViewModel viewModel)
        {
            using(IEasyTrainTicketsDbEntities dbContext = unitOfWorkFactory.CreateUnitOfWork())
            {
                List<Connection> connections = Session["connections"] as List<Connection>;
                foreach (var con in connections)
                {
                    con.Train = dbContext.Trains.Where(c => c.Id == con.Train.Id).First();
                    dbContext.Trains.Attach(con.Train);
                    foreach (var part in con.Parts)
                    {
                        part.Route = dbContext.Routes.Where(r => r.Id == part.Route.Id).First();
                        dbContext.Routes.Attach(part.Route);

                    }
                    
                    dbContext.Connections.Add(con);
                }
                dbContext.SaveChanges();
            }
            Session["connections"] = null;
            return View("MySuccess", new ErrorViewModel() { ErrorMessage = "Udało się dodać rozkład jazdy na wybrany dzień" });
        }

        [HttpPost]
        public ActionResult PrepareListConnections(DateViewModel dateViewModel)
        {
            List<Connection> connections;
            using (IEasyTrainTicketsDbEntities dbContext = unitOfWorkFactory.CreateUnitOfWork())
            {
                int number = dbContext.Connections.Where(c => c.Parts.FirstOrDefault().StartTime.Day == dateViewModel.Date.Day && c.Parts.FirstOrDefault().StartTime.Month == dateViewModel.Date.Month && c.Parts.FirstOrDefault().StartTime.Year == dateViewModel.Date.Year).Count();
                if (number > 0)
                {
                    return View("MyError", new ErrorViewModel() { ErrorMessage = "Na ten dzień istnieja już połączenia" });
                }
                connections = ConnectionsGenerator.PerDay(dateViewModel.Date, dbContext);
            }
            PagingInfo PagingInfo = new PagingInfo() { CurrentPage = 1, ItemsPerPage = PageSize, TotalItems = connections.Count };
            ListConnectionsViewModel viewModel = new ListConnectionsViewModel();
            viewModel.Show(connections, PagingInfo);
            Session["connections"] = connections;
            Session["Date"] = dateViewModel.Date;

            return View("ListConnections", viewModel);
        }

        public ActionResult ListConnections(int page)
        {
            List<Connection> connections = Session["connections"] as List<Connection>;
            PagingInfo PagingInfo = new PagingInfo() { CurrentPage = page, ItemsPerPage = PageSize, TotalItems = connections.Count };
            ListConnectionsViewModel viewModel = new ListConnectionsViewModel();
            viewModel.Show(connections, PagingInfo);
            ModelState.Clear();

            return View("ListConnections", viewModel);
        }

        public ActionResult PrepareAddConnection()
        {
            AddConnectionViewModel viewModel;
            using (IEasyTrainTicketsDbEntities dbContext = unitOfWorkFactory.CreateUnitOfWork())
            {
                viewModel = new AddConnectionViewModel(dbContext);
            }
            ViewBag.Date = (DateTime)Session["Date"];
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddConnectionParts(AddConnectionViewModel viewModel, string stringConnection)
        {
            if (viewModel.SelectRoute == null)
            {
                DateTime date = (DateTime)Session["Date"];
                viewModel.StartTime = date.Date + viewModel.TimeOfDay;
                using (IEasyTrainTicketsDbEntities dbContext = unitOfWorkFactory.CreateUnitOfWork())
                {
                    addConnectionModel.CreateConnection(viewModel, dbContext);
                }
            }
            else
            {
                using (IEasyTrainTicketsDbEntities dbContext = unitOfWorkFactory.CreateUnitOfWork())
                {
                    addConnectionModel.AddConnectionPart(viewModel, dbContext, JsonConvert.DeserializeObject<Connection>(stringConnection));
                }
            }
            ModelState.Clear();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddConnection(string stringConnection)
        {
            Connection connection = JsonConvert.DeserializeObject<Connection>(stringConnection);
            addConnectionModel.EndInitializationConnection(connection);

            if(Session["connections"] is List<Connection>)
            {
                List<Connection> connections = Session["connections"] as List<Connection>;
                connections.Add(connection);
                Session["connections"] = connections;
                return RedirectToAction("ListConnections", new { page = 1 });
            }
            else
            {
                using (IEasyTrainTicketsDbEntities dbContext = unitOfWorkFactory.CreateUnitOfWork())
                {
                    dbContext.Trains.Attach(connection.Train);
                    foreach (var part in connection.Parts)
                    {
                        dbContext.Routes.Attach(part.Route);
                 
                    }            
                    dbContext.Connections.Add(connection);
                    dbContext.SaveChanges();
                }
                   
                return View("MySuccess", new ErrorViewModel() { ErrorMessage = "Udało się dodać wybrane połączenie" });
            }
        }
    }
}

src/EasyTrainTickets3.WebUI/Views/AddConnections/AddConnectionParts.cshtml
@model EasyTrainTickets3.WebUI.Models.AddConnectionViewModel

@{
    ViewBag.Title = "Dodawanie połączenia";
}

<script>
    function validate() {
        if (@Model.Connection.Connection.Parts.Count == 0)
            $('#save').prop('disabled', true);
        else
            $('#save').prop('disabled', false);
    }
    $(document).ready(function () {
        validate();
        $('.lblUp1').click(function(){
            $('.txtUpDown1').val(parseInt($('.txtUpDown1').val(),10) + 1);
        });
        $('.lblDown1').click(function(){
            $('.txtUpDown1').val(parseInt($('.txtUpDown1').val(),10) - 1);
            
        });

        $('.lblUp2').click(function(){
            $('.txtUpDown2').val(parseInt($('.txtUpDown2').val(),10) + 1);
        });
        $('.lblDown2').click(function(){
            $('.txtUpDown2').val(parseInt($('.txtUpDown2').val(),10) - 1);
            
        });
    }); // koniec funkcji ready
</script>

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        
        <div class="row details">
            @foreach (var s in Model.Connection.Way)
            {
                <pre>@s</pre>
            }
        </div>

        @using (Html.BeginForm("AddConnectionParts", "AddConnections"))
        {
            <div class="form-group">
                <label>Wybierz drogę:</label>
                @Html.DropDownListFor(m => m.SelectRoute, new SelectList(Model.AvailableRoutes), "Wybierz opcję", new { @class = "form-control list" })
                @Html.ValidationMessageFor(m => m.SelectRoute, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label>Podaj rezerwę czasową:</label>
                @Html.TextBoxFor(m => m.Variance, new { @class = "form-control txtUpDown1", @readonly = "redaonly" })
                <label class="lblUp1 btn btn-default">+</label>
                <label class="lblDown1 btn btn-default">-</label>
                @Html.ValidationMessageFor(m => m.Variance, "", new { @class = "text-danger" })
            </div>

            if (Model.Connection.Connection.Parts.Count != 0)
            {
                <div class="form-group">
                    <label>Podaj czas postoju:</label>
                    @Html.TextBoxFor(m => m.StopTime, new { @class = "form-control txtUpDown2" })
                    <label class="lblUp2 btn btn-default">+</label>
                    <label class="lblDown2 btn btn-default">-</label>
                    @Html.ValidationMessageFor(m => m.StopTime, "", new { @class = "text-danger" })
                </div>
            }

            @Html.Hidden("stringConnection", Model.Connection.JsonString)
            @Html.HiddenFor(m => m.StartTime, Model.StartTime);
            <div class="text-center">
                <input type="submit" value="Dalej" class="btn btn-success" />
            </div>
        }
        <hr/>
        @using (Html.BeginForm("AddConnection", "AddConnections"))
        {
            @Html.Hidden("stringConnection", Model.Connection.JsonString)
            <div class="text-center">
                <input type="submit" id="save" value="Zapisz" class="btn btn-success" />
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/EasyTrainTickets3.WebUI/Views/AddConnections/Index.cshtml
@model EasyTrainTickets3.WebUI.Models.DateViewModel

@{
    ViewBag.Title = "Dodaj połączenia";
}

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm("PrepareListConnections", "AddConnections"))
        {
            <div class="form-group">
                <label>Data:</label>
                @Html.TextBoxFor(m => m.Date, new { @class = "form-control", @id = "datetimepicker", @Value = DateTime.Today.AddDays(1).ToShortDateString() })
                @Html.ValidationMessageFor(m => m.Date, "", new { @class = "text-danger" })
            </div>
            <div class="text-center">
                <input type="submit" value="Dalej" class="btn btn-success" />
            </div>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerydate")
    <script type="text/javascript">
    $(function () {
        $("#datetimepicker").datetimepicker({
            timepicker: false,
            format: 'Y-m-d',
            minDate: '+1'
        });
    });
    </script>
}

src/EasyTrainTickets3.WebUI/Views/AddConnections/ListConnections.cshtml
@model EasyTrainTickets3.WebUI.Models.ListConnectionsViewModel

@{
    ViewBag.Title = "Lista Połączeń";
}

<script>
    jQuery.fn.clickToggle = function (a, b) {
        function cb() { [b, a][this._tog ^= 1].call(this); }
        return this.on("click", cb);
    };

    $(document).ready(function () {
 $('.details').hide();
 $('.connection').clickToggle(
    	function() {
           $(this).next('.details').slideDown();
        },
        function() {
           $(this).next('.details').fadeOut();
      }
    ); // koniec funkcji toggle
}); // koniec funkcji ready
</script>

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        @foreach (var connection in Model.ListConnections)
        {
            <div class="row connection">
                <div class="row">
                    <div class="col-md-2">
                        @connection.Connection.StartPlace
                    </div>
                    <div class="col-md-2">
                        <span>@connection.Connection.Parts[0].StartTime.ToShortDateString()</span>
                    </div>
                    <div class="col-md-1">
                        <span>@connection.Connection.Parts[0].StartTime.ToShortTimeString()</span>
                    </div>
                    <div class="col-md-2">
                        <span>@connection.Connection.Name</span>
                    </div>
                    @using (Html.BeginForm("DeleteConnection", "AddConnections"))
                    {
                        @Html.Hidden("page", Model.PagingInfo.CurrentPage)
                        @Html.Hidden("stringConnection", connection.JsonString)
                        <div class="col-lg-1">
                            <input id="delete" class="btn btn-success" type="submit" value="Usuń pociąg" />
                        </div>
                    }
                </div>
                <div class="row">
                    <div class="col-lg-2">
                        @connection.Connection.EndPlace
                    </div>
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-1">
                        @connection.Connection.Parts.Last().EndTime.ToShortTimeString()
                    </div>
                </div>
            </div>
            <div class="row details">
                @foreach (var s in connection.Way)
                {
                    <pre>@s</pre>
                }
            </div>
            <hr/>
        }
    </div>

    @using (Html.BeginForm("PrepareAddConnection", "AddConnections"))
    {
        <div class="text-center">
            <input type="submit" value="Dodaj połączenie" class="btn btn-success" />
        </div>
    }
    <hr />
    @using (Html.BeginForm("AddConnections", "AddConnections"))
    {
        <div class="text-center">
            <input type="submit" value="Zapisz połączenia" class="btn btn-success" />
        </div>
    }
                <div class="pager pull-right">
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("ListConnections", new { page = x }))
                </div>

</div>

src/EasyTrainTickets3.WebUI/Views/AddConnections/PrepareAddConnection.cshtml
@model EasyTrainTickets3.WebUI.Models.AddConnectionViewModel

@{
    ViewBag.Title = "Dodawanie połączenia";
}

<div class="panel-success">
    <div class="panel-heading text-center"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm("AddConnectionParts", "AddConnections"))
        {
            <div class="form-group">
                <label>Nazwa pociągu:</label>
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control"})
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Rodzaj pociągu:</label>
                @Html.DropDownListFor(m => m.SelectTrain, new SelectList(Model.Trains), "Wybierz opcję", new {@class = "form-control list" })
                @Html.ValidationMessageFor(m => m.SelectTrain, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Data Odjazdu:</label>
                @Html.TextBoxFor(m => m.TimeOfDay, new { @class = "form-control", @id = "datetimepicker1", @Value = ViewBag.Date.ToShortTimeString() })
                @Html.ValidationMessageFor(m => m.TimeOfDay, "", new { @class = "text-danger" })
            </div>
            <div class="text-center">
                <input type="submit" value="Dalej" class="btn btn-success" />
            </div>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerydate")
<script type="text/javascript">
    $(function () {
        $("#datetimepicker1").datetimepicker({
            format: 'H:m',
            minDate: '0',
            datepicker: false
        });
    });
</script>
}